# Generated by Django 4.2.7 on 2025-08-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_urlclick_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
