# Generated by Django 4.2.7 on 2025-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_shortenedurl_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='urlclick',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
