# Generated by Django 4.2.7 on 2025-08-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('qr_type', models.CharField(choices=[('url', 'URL/Link'), ('file', 'File'), ('wifi', 'Wi-Fi'), ('text', 'Text'), ('vcard', 'Contact (vCard)'), ('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('calendar', 'Calendar Event'), ('social', 'Social Media')], max_length=20)),
                ('is_dynamic', models.BooleanField(default=False, help_text='Dynamic QR codes can be updated without regenerating')),
                ('content', models.JSONField(default=dict, help_text='Stores different data based on QR type')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_image_url', models.URLField(blank=True, help_text='Cloudinary URL for the QR code image')),
                ('short_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('redirect_url', models.URLField(blank=True, help_text='For dynamic QR codes, points to our redirect endpoint')),
                ('customization', models.JSONField(default=dict, help_text='Colors, size, logo, etc.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_codes.qrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qr_files/')),
                ('file_url', models.URLField(blank=True, help_text='Cloudinary URL')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='qr_codes.qrcode')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
